[2024-07-19T09:15:36.646+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_operator.python_job manual__2024-07-19T09:15:35.872124+00:00 [queued]>
[2024-07-19T09:15:36.656+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_operator.python_job manual__2024-07-19T09:15:35.872124+00:00 [queued]>
[2024-07-19T09:15:36.657+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-07-19T09:15:36.680+0000] {taskinstance.py:2217} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-07-19 09:15:35.872124+00:00
[2024-07-19T09:15:36.692+0000] {standard_task_runner.py:60} INFO - Started process 2579 to run task
[2024-07-19T09:15:36.699+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spark_operator', 'python_job', 'manual__2024-07-19T09:15:35.872124+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp23auh43r']
[2024-07-19T09:15:36.701+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask python_job
[2024-07-19T09:15:36.764+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_operator.python_job manual__2024-07-19T09:15:35.872124+00:00 [running]> on host e0be4a68a7ce
[2024-07-19T09:15:36.898+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_operator' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T09:15:35.872124+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T09:15:35.872124+00:00'
[2024-07-19T09:15:36.909+0000] {spark_submit.py:271} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-07-19T09:15:36.913+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=local[*] --conf spark.yarn.appMasterEnv.SPARK_MASTER_HOST=172.19.0.2 --name arrow-spark --verbose /plugins/pyspark.py
[2024-07-19T09:15:36.991+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-07-19T09:15:39.269+0000] {spark_submit.py:571} INFO - Using properties file: null
[2024-07-19T09:15:39.368+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-07-19T09:15:39.369+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-07-19T09:15:39.370+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-07-19T09:15:39.370+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-07-19T09:15:39.371+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-07-19T09:15:39.371+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-07-19T09:15:39.372+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-07-19T09:15:39.372+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-07-19T09:15:39.373+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-07-19T09:15:39.373+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-07-19T09:15:39.374+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-07-19T09:15:39.409+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.yarn.appMasterEnv.SPARK_MASTER_HOST=172.19.0.2 --name arrow-spark --verbose /plugins/pyspark.py. Error code is: 1.
[2024-07-19T09:15:39.412+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_operator, task_id=python_job, execution_date=20240719T091535, start_date=20240719T091536, end_date=20240719T091539
[2024-07-19T09:15:39.432+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task python_job (Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.yarn.appMasterEnv.SPARK_MASTER_HOST=172.19.0.2 --name arrow-spark --verbose /plugins/pyspark.py. Error code is: 1.; 2579)
[2024-07-19T09:15:39.458+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-19T09:15:39.476+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
